.\" Man page for Kylin-vpn
.TH KYLIN-NM-VPN 1 "26 January 2026" "UKUI Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
kylin-vpn \- The tool for the kylin-nm
.SH "SYNOPSIS"
.B kylin-vpn
.SH "DESCRIPTION"
The \fBkylin-vpn\fR program is a part of the kylin-nm, It provides a user configuration interface for VPN.
.PP
This manual page documents the \fBkylin-vpn\fR command.
.P
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
https://gitee.com/openkylin/kylin-nm/issues
.SH "AUTHORS"
.SS This Man Page has been written for the UKUI Desktop Environment by:
maqiang <maqiang@kylinos.cn> (2026)
.SH "SEE ALSO"