#############################################################################
# Makefile for building: kylin-nm
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  kylin-nm.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile kylin-nm.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = kylin-nm1.0.0
DISTDIR = /home/chenlelin/kylin-nm/kylin-nm-master/.tmp/kylin-nm1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) -lQt5X11Extras -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		ksimplenm.cpp \
		oneconnform.cpp \
		confform.cpp \
		kylin-network-interface.c \
		backthread.cpp \
		onelancform.cpp \
		loadingdiv.cpp \
		dlgconnhidwifi.cpp \
		dlgconnhidwifisecfast.cpp \
		dlgconnhidwifisectunneltls.cpp \
		dlgconnhidwifisecpeap.cpp \
		dlgconnhidwifisectls.cpp \
		dlgconnhidwifisecleap.cpp \
		dlgconnhidwifisecpwd.cpp \
		dlgconnhidwifiwep.cpp \
		dlgconnhidwifileap.cpp \
		dlgconnhidwifiwpa.cpp qrc_nmqrc.cpp \
		moc_mainwindow.cpp \
		moc_ksimplenm.cpp \
		moc_oneconnform.cpp \
		moc_confform.cpp \
		moc_backthread.cpp \
		moc_onelancform.cpp \
		moc_loadingdiv.cpp \
		moc_dlgconnhidwifi.cpp \
		moc_dlgconnhidwifisecfast.cpp \
		moc_dlgconnhidwifisectunneltls.cpp \
		moc_dlgconnhidwifisecpeap.cpp \
		moc_dlgconnhidwifisectls.cpp \
		moc_dlgconnhidwifisecleap.cpp \
		moc_dlgconnhidwifisecpwd.cpp \
		moc_dlgconnhidwifiwep.cpp \
		moc_dlgconnhidwifileap.cpp \
		moc_dlgconnhidwifiwpa.cpp
OBJECTS       = main.o \
		mainwindow.o \
		ksimplenm.o \
		oneconnform.o \
		confform.o \
		kylin-network-interface.o \
		backthread.o \
		onelancform.o \
		loadingdiv.o \
		dlgconnhidwifi.o \
		dlgconnhidwifisecfast.o \
		dlgconnhidwifisectunneltls.o \
		dlgconnhidwifisecpeap.o \
		dlgconnhidwifisectls.o \
		dlgconnhidwifisecleap.o \
		dlgconnhidwifisecpwd.o \
		dlgconnhidwifiwep.o \
		dlgconnhidwifileap.o \
		dlgconnhidwifiwpa.o \
		qrc_nmqrc.o \
		moc_mainwindow.o \
		moc_ksimplenm.o \
		moc_oneconnform.o \
		moc_confform.o \
		moc_backthread.o \
		moc_onelancform.o \
		moc_loadingdiv.o \
		moc_dlgconnhidwifi.o \
		moc_dlgconnhidwifisecfast.o \
		moc_dlgconnhidwifisectunneltls.o \
		moc_dlgconnhidwifisecpeap.o \
		moc_dlgconnhidwifisectls.o \
		moc_dlgconnhidwifisecleap.o \
		moc_dlgconnhidwifisecpwd.o \
		moc_dlgconnhidwifiwep.o \
		moc_dlgconnhidwifileap.o \
		moc_dlgconnhidwifiwpa.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		kylin-nm.pro mainwindow.h \
		ksimplenm.h \
		oneconnform.h \
		confform.h \
		kylin-network-interface.h \
		backthread.h \
		onelancform.h \
		loadingdiv.h \
		dlgconnhidwifi.h \
		dlgconnhidwifisecfast.h \
		dlgconnhidwifisectunneltls.h \
		dlgconnhidwifisecpeap.h \
		dlgconnhidwifisectls.h \
		dlgconnhidwifisecleap.h \
		dlgconnhidwifisecpwd.h \
		dlgconnhidwifiwep.h \
		dlgconnhidwifileap.h \
		dlgconnhidwifiwpa.h \
		kylinheadfile.h main.cpp \
		mainwindow.cpp \
		ksimplenm.cpp \
		oneconnform.cpp \
		confform.cpp \
		kylin-network-interface.c \
		backthread.cpp \
		onelancform.cpp \
		loadingdiv.cpp \
		dlgconnhidwifi.cpp \
		dlgconnhidwifisecfast.cpp \
		dlgconnhidwifisectunneltls.cpp \
		dlgconnhidwifisecpeap.cpp \
		dlgconnhidwifisectls.cpp \
		dlgconnhidwifisecleap.cpp \
		dlgconnhidwifisecpwd.cpp \
		dlgconnhidwifiwep.cpp \
		dlgconnhidwifileap.cpp \
		dlgconnhidwifiwpa.cpp
QMAKE_TARGET  = kylin-nm
DESTDIR       = 
TARGET        = kylin-nm


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_oneconnform.h ui_confform.h ui_onelancform.h ui_dlgconnhidwifi.h ui_dlgconnhidwifisecfast.h ui_dlgconnhidwifisectunneltls.h ui_dlgconnhidwifisecpeap.h ui_dlgconnhidwifisectls.h ui_dlgconnhidwifisecleap.h ui_dlgconnhidwifisecpwd.h ui_dlgconnhidwifiwep.h ui_dlgconnhidwifileap.h ui_dlgconnhidwifiwpa.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: kylin-nm.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		kylin-nm.pro \
		nmqrc.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5X11Extras.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile kylin-nm.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
kylin-nm.pro:
nmqrc.qrc:
/usr/lib/x86_64-linux-gnu/libQt5X11Extras.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile kylin-nm.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents nmqrc.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h ksimplenm.h oneconnform.h confform.h kylin-network-interface.h backthread.h onelancform.h loadingdiv.h dlgconnhidwifi.h dlgconnhidwifisecfast.h dlgconnhidwifisectunneltls.h dlgconnhidwifisecpeap.h dlgconnhidwifisectls.h dlgconnhidwifisecleap.h dlgconnhidwifisecpwd.h dlgconnhidwifiwep.h dlgconnhidwifileap.h dlgconnhidwifiwpa.h kylinheadfile.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp ksimplenm.cpp oneconnform.cpp confform.cpp kylin-network-interface.c backthread.cpp onelancform.cpp loadingdiv.cpp dlgconnhidwifi.cpp dlgconnhidwifisecfast.cpp dlgconnhidwifisectunneltls.cpp dlgconnhidwifisecpeap.cpp dlgconnhidwifisectls.cpp dlgconnhidwifisecleap.cpp dlgconnhidwifisecpwd.cpp dlgconnhidwifiwep.cpp dlgconnhidwifileap.cpp dlgconnhidwifiwpa.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui oneconnform.ui confform.ui onelancform.ui dlgconnhidwifi.ui dlgconnhidwifisecfast.ui dlgconnhidwifisectunneltls.ui dlgconnhidwifisecpeap.ui dlgconnhidwifisectls.ui dlgconnhidwifisecleap.ui dlgconnhidwifisecpwd.ui dlgconnhidwifiwep.ui dlgconnhidwifileap.ui dlgconnhidwifiwpa.ui $(DISTDIR)/
	$(COPY_FILE) --parents res/kylin-nm_zh_CN.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_nmqrc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_nmqrc.cpp
qrc_nmqrc.cpp: nmqrc.qrc \
		/usr/lib/qt5/bin/rcc \
		res/kylin-nm_zh_CN.qm \
		res/wifi.png \
		res/s/setting.png \
		res/s/wifi-full.png \
		res/s/wifi-full-secure.png \
		res/s/wifi-medium.png \
		res/s/network-line.png \
		res/s/wifi-none-secure.png \
		res/s/pnormal.png \
		res/s/pbad.png \
		res/s/wifi-low-secure.png \
		res/s/wifi-high.png \
		res/s/network-offline.png \
		res/s/wifi-medium-secure.png \
		res/s/wifi-none.png \
		res/s/wifi-high-secure.png \
		res/s/wifi-low.png \
		res/s/pgood.png \
		res/s/conning-b/2.png \
		res/s/conning-b/6.png \
		res/s/conning-b/10.png \
		res/s/conning-b/1.png \
		res/s/conning-b/5.png \
		res/s/conning-b/9.png \
		res/s/conning-b/4.png \
		res/s/conning-b/8.png \
		res/s/conning-b/12.png \
		res/s/conning-b/3.png \
		res/s/conning-b/7.png \
		res/s/conning-b/11.png \
		res/s/rescan/2.png \
		res/s/rescan/6.png \
		res/s/rescan/10.png \
		res/s/rescan/1.png \
		res/s/rescan/5.png \
		res/s/rescan/9.png \
		res/s/rescan/4.png \
		res/s/rescan/8.png \
		res/s/rescan/12.png \
		res/s/rescan/3.png \
		res/s/rescan/7.png \
		res/s/rescan/11.png \
		res/s/conning-s/2.png \
		res/s/conning-s/6.png \
		res/s/conning-s/10.png \
		res/s/conning-s/1.png \
		res/s/conning-s/5.png \
		res/s/conning-s/9.png \
		res/s/conning-s/4.png \
		res/s/conning-s/8.png \
		res/s/conning-s/12.png \
		res/s/conning-s/3.png \
		res/s/conning-s/7.png \
		res/s/conning-s/11.png \
		res/h/show-pwd.png \
		res/h/no-pwd-wifi.png \
		res/h/add-hide-wifi.png \
		res/h/hide-pwd.png \
		res/h/right-pwd.png \
		res/h/add-hide-wifi.svg \
		res/g/down_arrow.png \
		res/g/triangle.png \
		res/x/wifi-error.png \
		res/x/network-offline.png \
		res/x/wifi-offline.png \
		res/x/network-line.png \
		res/x/setup.png \
		res/x/network-error.png \
		res/x/wifi-line.png
	/usr/lib/qt5/bin/rcc -name nmqrc nmqrc.qrc -o qrc_nmqrc.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_ksimplenm.cpp moc_oneconnform.cpp moc_confform.cpp moc_backthread.cpp moc_onelancform.cpp moc_loadingdiv.cpp moc_dlgconnhidwifi.cpp moc_dlgconnhidwifisecfast.cpp moc_dlgconnhidwifisectunneltls.cpp moc_dlgconnhidwifisecpeap.cpp moc_dlgconnhidwifisectls.cpp moc_dlgconnhidwifisecleap.cpp moc_dlgconnhidwifisecpwd.cpp moc_dlgconnhidwifiwep.cpp moc_dlgconnhidwifileap.cpp moc_dlgconnhidwifiwpa.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_ksimplenm.cpp moc_oneconnform.cpp moc_confform.cpp moc_backthread.cpp moc_onelancform.cpp moc_loadingdiv.cpp moc_dlgconnhidwifi.cpp moc_dlgconnhidwifisecfast.cpp moc_dlgconnhidwifisectunneltls.cpp moc_dlgconnhidwifisecpeap.cpp moc_dlgconnhidwifisectls.cpp moc_dlgconnhidwifisecleap.cpp moc_dlgconnhidwifisecpwd.cpp moc_dlgconnhidwifiwep.cpp moc_dlgconnhidwifileap.cpp moc_dlgconnhidwifiwpa.cpp
moc_mainwindow.cpp: ksimplenm.h \
		loadingdiv.h \
		kylin-network-interface.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_ksimplenm.cpp: ksimplenm.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ksimplenm.h -o moc_ksimplenm.cpp

moc_oneconnform.cpp: confform.h \
		kylin-network-interface.h \
		backthread.h \
		ksimplenm.h \
		oneconnform.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include oneconnform.h -o moc_oneconnform.cpp

moc_confform.cpp: confform.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include confform.h -o moc_confform.cpp

moc_backthread.cpp: backthread.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include backthread.h -o moc_backthread.cpp

moc_onelancform.cpp: confform.h \
		kylin-network-interface.h \
		backthread.h \
		ksimplenm.h \
		onelancform.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include onelancform.h -o moc_onelancform.cpp

moc_loadingdiv.cpp: loadingdiv.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include loadingdiv.h -o moc_loadingdiv.cpp

moc_dlgconnhidwifi.cpp: dlgconnhidwifi.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dlgconnhidwifi.h -o moc_dlgconnhidwifi.cpp

moc_dlgconnhidwifisecfast.cpp: dlgconnhidwifisecfast.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dlgconnhidwifisecfast.h -o moc_dlgconnhidwifisecfast.cpp

moc_dlgconnhidwifisectunneltls.cpp: dlgconnhidwifisectunneltls.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dlgconnhidwifisectunneltls.h -o moc_dlgconnhidwifisectunneltls.cpp

moc_dlgconnhidwifisecpeap.cpp: dlgconnhidwifisecpeap.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dlgconnhidwifisecpeap.h -o moc_dlgconnhidwifisecpeap.cpp

moc_dlgconnhidwifisectls.cpp: dlgconnhidwifisectls.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dlgconnhidwifisectls.h -o moc_dlgconnhidwifisectls.cpp

moc_dlgconnhidwifisecleap.cpp: dlgconnhidwifisecleap.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dlgconnhidwifisecleap.h -o moc_dlgconnhidwifisecleap.cpp

moc_dlgconnhidwifisecpwd.cpp: dlgconnhidwifisecpwd.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dlgconnhidwifisecpwd.h -o moc_dlgconnhidwifisecpwd.cpp

moc_dlgconnhidwifiwep.cpp: dlgconnhidwifiwep.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dlgconnhidwifiwep.h -o moc_dlgconnhidwifiwep.cpp

moc_dlgconnhidwifileap.cpp: dlgconnhidwifileap.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dlgconnhidwifileap.h -o moc_dlgconnhidwifileap.cpp

moc_dlgconnhidwifiwpa.cpp: dlgconnhidwifiwpa.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/chenlelin/kylin-nm/kylin-nm-master -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtX11Extras -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dlgconnhidwifiwpa.h -o moc_dlgconnhidwifiwpa.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_oneconnform.h ui_confform.h ui_onelancform.h ui_dlgconnhidwifi.h ui_dlgconnhidwifisecfast.h ui_dlgconnhidwifisectunneltls.h ui_dlgconnhidwifisecpeap.h ui_dlgconnhidwifisectls.h ui_dlgconnhidwifisecleap.h ui_dlgconnhidwifisecpwd.h ui_dlgconnhidwifiwep.h ui_dlgconnhidwifileap.h ui_dlgconnhidwifiwpa.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_oneconnform.h ui_confform.h ui_onelancform.h ui_dlgconnhidwifi.h ui_dlgconnhidwifisecfast.h ui_dlgconnhidwifisectunneltls.h ui_dlgconnhidwifisecpeap.h ui_dlgconnhidwifisectls.h ui_dlgconnhidwifisecleap.h ui_dlgconnhidwifisecpwd.h ui_dlgconnhidwifiwep.h ui_dlgconnhidwifileap.h ui_dlgconnhidwifiwpa.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_oneconnform.h: oneconnform.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic oneconnform.ui -o ui_oneconnform.h

ui_confform.h: confform.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic confform.ui -o ui_confform.h

ui_onelancform.h: onelancform.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic onelancform.ui -o ui_onelancform.h

ui_dlgconnhidwifi.h: dlgconnhidwifi.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dlgconnhidwifi.ui -o ui_dlgconnhidwifi.h

ui_dlgconnhidwifisecfast.h: dlgconnhidwifisecfast.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dlgconnhidwifisecfast.ui -o ui_dlgconnhidwifisecfast.h

ui_dlgconnhidwifisectunneltls.h: dlgconnhidwifisectunneltls.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dlgconnhidwifisectunneltls.ui -o ui_dlgconnhidwifisectunneltls.h

ui_dlgconnhidwifisecpeap.h: dlgconnhidwifisecpeap.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dlgconnhidwifisecpeap.ui -o ui_dlgconnhidwifisecpeap.h

ui_dlgconnhidwifisectls.h: dlgconnhidwifisectls.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dlgconnhidwifisectls.ui -o ui_dlgconnhidwifisectls.h

ui_dlgconnhidwifisecleap.h: dlgconnhidwifisecleap.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dlgconnhidwifisecleap.ui -o ui_dlgconnhidwifisecleap.h

ui_dlgconnhidwifisecpwd.h: dlgconnhidwifisecpwd.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dlgconnhidwifisecpwd.ui -o ui_dlgconnhidwifisecpwd.h

ui_dlgconnhidwifiwep.h: dlgconnhidwifiwep.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dlgconnhidwifiwep.ui -o ui_dlgconnhidwifiwep.h

ui_dlgconnhidwifileap.h: dlgconnhidwifileap.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dlgconnhidwifileap.ui -o ui_dlgconnhidwifileap.h

ui_dlgconnhidwifiwpa.h: dlgconnhidwifiwpa.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic dlgconnhidwifiwpa.ui -o ui_dlgconnhidwifiwpa.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		ksimplenm.h \
		loadingdiv.h \
		kylin-network-interface.h \
		dlgconnhidwifi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ksimplenm.h \
		loadingdiv.h \
		kylin-network-interface.h \
		ui_mainwindow.h \
		oneconnform.h \
		confform.h \
		backthread.h \
		onelancform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

ksimplenm.o: ksimplenm.cpp ksimplenm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ksimplenm.o ksimplenm.cpp

oneconnform.o: oneconnform.cpp oneconnform.h \
		confform.h \
		kylin-network-interface.h \
		backthread.h \
		ksimplenm.h \
		ui_oneconnform.h \
		mainwindow.h \
		loadingdiv.h \
		dlgconnhidwifi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oneconnform.o oneconnform.cpp

confform.o: confform.cpp confform.h \
		ui_confform.h \
		kylin-network-interface.h \
		backthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o confform.o confform.cpp

kylin-network-interface.o: kylin-network-interface.c kylin-network-interface.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o kylin-network-interface.o kylin-network-interface.c

backthread.o: backthread.cpp backthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o backthread.o backthread.cpp

onelancform.o: onelancform.cpp onelancform.h \
		confform.h \
		kylin-network-interface.h \
		backthread.h \
		ksimplenm.h \
		ui_onelancform.h \
		mainwindow.h \
		loadingdiv.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o onelancform.o onelancform.cpp

loadingdiv.o: loadingdiv.cpp loadingdiv.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loadingdiv.o loadingdiv.cpp

dlgconnhidwifi.o: dlgconnhidwifi.cpp dlgconnhidwifi.h \
		kylinheadfile.h \
		dlgconnhidwifileap.h \
		dlgconnhidwifisecfast.h \
		dlgconnhidwifisecleap.h \
		dlgconnhidwifisecpeap.h \
		dlgconnhidwifisecpwd.h \
		dlgconnhidwifisectls.h \
		dlgconnhidwifisectunneltls.h \
		dlgconnhidwifiwep.h \
		dlgconnhidwifiwpa.h \
		ui_dlgconnhidwifi.h \
		backthread.h \
		mainwindow.h \
		ksimplenm.h \
		loadingdiv.h \
		kylin-network-interface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlgconnhidwifi.o dlgconnhidwifi.cpp

dlgconnhidwifisecfast.o: dlgconnhidwifisecfast.cpp dlgconnhidwifisecfast.h \
		ui_dlgconnhidwifisecfast.h \
		kylinheadfile.h \
		dlgconnhidwifi.h \
		dlgconnhidwifileap.h \
		dlgconnhidwifisecleap.h \
		dlgconnhidwifisecpeap.h \
		dlgconnhidwifisecpwd.h \
		dlgconnhidwifisectls.h \
		dlgconnhidwifisectunneltls.h \
		dlgconnhidwifiwep.h \
		dlgconnhidwifiwpa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlgconnhidwifisecfast.o dlgconnhidwifisecfast.cpp

dlgconnhidwifisectunneltls.o: dlgconnhidwifisectunneltls.cpp dlgconnhidwifisectunneltls.h \
		ui_dlgconnhidwifisectunneltls.h \
		kylinheadfile.h \
		dlgconnhidwifi.h \
		dlgconnhidwifileap.h \
		dlgconnhidwifisecfast.h \
		dlgconnhidwifisecleap.h \
		dlgconnhidwifisecpeap.h \
		dlgconnhidwifisecpwd.h \
		dlgconnhidwifisectls.h \
		dlgconnhidwifiwep.h \
		dlgconnhidwifiwpa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlgconnhidwifisectunneltls.o dlgconnhidwifisectunneltls.cpp

dlgconnhidwifisecpeap.o: dlgconnhidwifisecpeap.cpp dlgconnhidwifisecpeap.h \
		ui_dlgconnhidwifisecpeap.h \
		kylinheadfile.h \
		dlgconnhidwifi.h \
		dlgconnhidwifileap.h \
		dlgconnhidwifisecfast.h \
		dlgconnhidwifisecleap.h \
		dlgconnhidwifisecpwd.h \
		dlgconnhidwifisectls.h \
		dlgconnhidwifisectunneltls.h \
		dlgconnhidwifiwep.h \
		dlgconnhidwifiwpa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlgconnhidwifisecpeap.o dlgconnhidwifisecpeap.cpp

dlgconnhidwifisectls.o: dlgconnhidwifisectls.cpp ui_dlgconnhidwifisectls.h \
		kylinheadfile.h \
		dlgconnhidwifi.h \
		dlgconnhidwifileap.h \
		dlgconnhidwifisecfast.h \
		dlgconnhidwifisecleap.h \
		dlgconnhidwifisecpeap.h \
		dlgconnhidwifisecpwd.h \
		dlgconnhidwifisectls.h \
		dlgconnhidwifisectunneltls.h \
		dlgconnhidwifiwep.h \
		dlgconnhidwifiwpa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlgconnhidwifisectls.o dlgconnhidwifisectls.cpp

dlgconnhidwifisecleap.o: dlgconnhidwifisecleap.cpp dlgconnhidwifisecleap.h \
		ui_dlgconnhidwifisecleap.h \
		kylinheadfile.h \
		dlgconnhidwifi.h \
		dlgconnhidwifileap.h \
		dlgconnhidwifisecfast.h \
		dlgconnhidwifisecpeap.h \
		dlgconnhidwifisecpwd.h \
		dlgconnhidwifisectls.h \
		dlgconnhidwifisectunneltls.h \
		dlgconnhidwifiwep.h \
		dlgconnhidwifiwpa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlgconnhidwifisecleap.o dlgconnhidwifisecleap.cpp

dlgconnhidwifisecpwd.o: dlgconnhidwifisecpwd.cpp dlgconnhidwifisecpwd.h \
		ui_dlgconnhidwifisecpwd.h \
		kylinheadfile.h \
		dlgconnhidwifi.h \
		dlgconnhidwifileap.h \
		dlgconnhidwifisecfast.h \
		dlgconnhidwifisecleap.h \
		dlgconnhidwifisecpeap.h \
		dlgconnhidwifisectls.h \
		dlgconnhidwifisectunneltls.h \
		dlgconnhidwifiwep.h \
		dlgconnhidwifiwpa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlgconnhidwifisecpwd.o dlgconnhidwifisecpwd.cpp

dlgconnhidwifiwep.o: dlgconnhidwifiwep.cpp ui_dlgconnhidwifiwep.h \
		kylinheadfile.h \
		dlgconnhidwifi.h \
		dlgconnhidwifileap.h \
		dlgconnhidwifisecfast.h \
		dlgconnhidwifisecleap.h \
		dlgconnhidwifisecpeap.h \
		dlgconnhidwifisecpwd.h \
		dlgconnhidwifisectls.h \
		dlgconnhidwifisectunneltls.h \
		dlgconnhidwifiwep.h \
		dlgconnhidwifiwpa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlgconnhidwifiwep.o dlgconnhidwifiwep.cpp

dlgconnhidwifileap.o: dlgconnhidwifileap.cpp ui_dlgconnhidwifileap.h \
		kylinheadfile.h \
		dlgconnhidwifi.h \
		dlgconnhidwifileap.h \
		dlgconnhidwifisecfast.h \
		dlgconnhidwifisecleap.h \
		dlgconnhidwifisecpeap.h \
		dlgconnhidwifisecpwd.h \
		dlgconnhidwifisectls.h \
		dlgconnhidwifisectunneltls.h \
		dlgconnhidwifiwep.h \
		dlgconnhidwifiwpa.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlgconnhidwifileap.o dlgconnhidwifileap.cpp

dlgconnhidwifiwpa.o: dlgconnhidwifiwpa.cpp dlgconnhidwifiwpa.h \
		ui_dlgconnhidwifiwpa.h \
		kylinheadfile.h \
		dlgconnhidwifi.h \
		dlgconnhidwifileap.h \
		dlgconnhidwifisecfast.h \
		dlgconnhidwifisecleap.h \
		dlgconnhidwifisecpeap.h \
		dlgconnhidwifisecpwd.h \
		dlgconnhidwifisectls.h \
		dlgconnhidwifisectunneltls.h \
		dlgconnhidwifiwep.h \
		backthread.h \
		mainwindow.h \
		ksimplenm.h \
		loadingdiv.h \
		kylin-network-interface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlgconnhidwifiwpa.o dlgconnhidwifiwpa.cpp

qrc_nmqrc.o: qrc_nmqrc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_nmqrc.o qrc_nmqrc.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_ksimplenm.o: moc_ksimplenm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ksimplenm.o moc_ksimplenm.cpp

moc_oneconnform.o: moc_oneconnform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_oneconnform.o moc_oneconnform.cpp

moc_confform.o: moc_confform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_confform.o moc_confform.cpp

moc_backthread.o: moc_backthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_backthread.o moc_backthread.cpp

moc_onelancform.o: moc_onelancform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_onelancform.o moc_onelancform.cpp

moc_loadingdiv.o: moc_loadingdiv.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loadingdiv.o moc_loadingdiv.cpp

moc_dlgconnhidwifi.o: moc_dlgconnhidwifi.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dlgconnhidwifi.o moc_dlgconnhidwifi.cpp

moc_dlgconnhidwifisecfast.o: moc_dlgconnhidwifisecfast.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dlgconnhidwifisecfast.o moc_dlgconnhidwifisecfast.cpp

moc_dlgconnhidwifisectunneltls.o: moc_dlgconnhidwifisectunneltls.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dlgconnhidwifisectunneltls.o moc_dlgconnhidwifisectunneltls.cpp

moc_dlgconnhidwifisecpeap.o: moc_dlgconnhidwifisecpeap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dlgconnhidwifisecpeap.o moc_dlgconnhidwifisecpeap.cpp

moc_dlgconnhidwifisectls.o: moc_dlgconnhidwifisectls.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dlgconnhidwifisectls.o moc_dlgconnhidwifisectls.cpp

moc_dlgconnhidwifisecleap.o: moc_dlgconnhidwifisecleap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dlgconnhidwifisecleap.o moc_dlgconnhidwifisecleap.cpp

moc_dlgconnhidwifisecpwd.o: moc_dlgconnhidwifisecpwd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dlgconnhidwifisecpwd.o moc_dlgconnhidwifisecpwd.cpp

moc_dlgconnhidwifiwep.o: moc_dlgconnhidwifiwep.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dlgconnhidwifiwep.o moc_dlgconnhidwifiwep.cpp

moc_dlgconnhidwifileap.o: moc_dlgconnhidwifileap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dlgconnhidwifileap.o moc_dlgconnhidwifileap.cpp

moc_dlgconnhidwifiwpa.o: moc_dlgconnhidwifiwpa.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dlgconnhidwifiwpa.o moc_dlgconnhidwifiwpa.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_shells: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/kylin-nm/shell/ || mkdir -p $(INSTALL_ROOT)/usr/share/kylin-nm/shell/
	-$(QINSTALL_PROGRAM) /home/chenlelin/kylin-nm/kylin-nm-master/connup.sh $(INSTALL_ROOT)/usr/share/kylin-nm/shell/connup.sh
	-strip $(INSTALL_ROOT)/usr/share/kylin-nm/shell/connup.sh

uninstall_shells: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/kylin-nm/shell/connup.sh
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/kylin-nm/shell/ 


install_desktop: first FORCE
	@test -d $(INSTALL_ROOT)/etc/xdg/autostart/ || mkdir -p $(INSTALL_ROOT)/etc/xdg/autostart/
	-$(QINSTALL) /home/chenlelin/kylin-nm/kylin-nm-master/kylin-nm.desktop $(INSTALL_ROOT)/etc/xdg/autostart/kylin-nm.desktop

uninstall_desktop: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/etc/xdg/autostart/kylin-nm.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/etc/xdg/autostart/ 


install: install_target install_shells install_desktop  FORCE

uninstall: uninstall_target uninstall_shells uninstall_desktop  FORCE

FORCE:

