TEMPLATE = subdirs
SUBDIRS += \
sys-dbus-register/main/main.pro \
sys-dbus-register/sys-dbus-register-test.pro \
sys-dbus-register/proxyServer/proxyServer-test.pro \
sys-dbus-register/kyarping/kylinipv4arping/kylinipv4arping-test.pro \
sys-dbus-register/kyarping/kylinipv6arping/kylinipv6arping-test.pro \
sys-dbus-netctrl/kylin/common/test_kylin_async_task.pro \
sys-dbus-netctrl/kylin/common/test_kylin_cfgInfo.pro \
#sys-dbus-netctrl/kylin/common/test_kylin_common.pro \
sys-dbus-netctrl/kylin/netControl/kylin_netctrol_server_interface/kylin_netctrol_server_interface-test.pro \
sys-dbus-netctrl/kylin/netControl/kylin_hedron_log/kylin_hedron_log-test.pro \
#plugins/vpn/vpn-test.pro \
#plugins/vpn/itemframe-test.pro \
#plugins/vpn/vpnitem-test.pro \
#plugins/mobilehotspot/mobilehotspotwidget/mobilehotspotwidget-test.pro \
#plugins/mobilehotspot/test_connectdevlistitem.pro \
#plugins/mobilehotspot/blacklistitem/blacklistitem-test.pro \
#plugins/mobilehotspot/connectdevpage/connectdevpage-test.pro \
#plugins/mobilehotspot/blacklistpage/blacklistpage-test.pro \
#plugins/mobilehotspot/mobilehotspot-test.pro \
#plugins/netconnect/deviceframe/deviceframe-test.pro \
#plugins/netconnect/lanitem-test.pro \
#plugins/netconnect/netconnect-test.pro \
#plugins/netconnect/itemframe-test.pro \
#plugins/proxy/aptproxydialog/aptproxydialog-test.pro \
#plugins/proxy/proxy/proxy-test.pro \
#plugins/component/AddBtn/test_grayinfobutton.pro \
#plugins/component/DrownLabel/drownlabel-test.pro \
#plugins/component/InfoButton/test_infobutton.pro \
#plugins/component/SwitchButton/switchbutton-test.pro \
#plugins/wlanconnect/wlanitem/wlanitem-test.pro \
#plugins/wlanconnect/deviceframe/deviceframe-test.pro \
#plugins/wlanconnect/itemframe-test.pro \
#plugins/wlanconnect/wlanconnect-test.pro \
qml-network/plugin/knmdatakeeper/knmdatakeeper-test.pro \
qml-network/plugin/knmwlandatakeeper/knmwlandatakeeper-test.pro \
qml-network/plugin/knmlandatakeeper/knmlandatakeeper-test.pro \
qml-network/plugin/netdevice/netdevice-test.pro \
qml-network/plugin/knmdbuscaller/knmdbuscaller-test.pro \
qml-network/plugin/networkqml_plugin/networkqml_plugin-test.pro \
qml-network/plugin/knminterface/knminterface-test.pro \
qml-network/plugin/wirelessconnectionmodel/wirelessconnectionmodel-test.pro \
#src-vpn/main/test_main.pro \
#src-vpn/backend/vpndbusadaptor/test_vpndbusadaptor.pro \
#src-vpn/frontend/vpnobject/test_vpnobject.pro \
#src-vpn/frontend/list-items/test_vpnlistitem.pro \
#src-vpn/frontend/single-pages/vpnpage/vpnpage-test.pro \
#src-vpn/frontend/single-pages/singlepage/singlepage-test.pro \
#src-vpn/frontend/vpndetails/vpnipv4page-test.pro \
#src-vpn/frontend/vpndetails/vpnaddpage-test.pro \
#src-vpn/frontend/vpndetails/vpnconfigpage/vpnconfigpage-test.pro \
#src-vpn/frontend/vpndetails/vpnipv6page-test.pro \
#src-vpn/frontend/vpndetails/vpndetail-test.pro \
#src-vpn/frontend/vpndetails/vpndetail/vpndetail-test.pro \
#src-vpn/frontend/vpndetails/vpnadvancedpage/vpnadvancedpage-test.pro \
#src-vpn/singleapplication/qt-single-application-test.pro \
#src-vpn/singleapplication/qt-local-peer/qt-local-peer-test.pro \
#src-vpn/singleapplication/qt-locked-file-test.pro \
#src/backend/hotspot/test_dlghotspotcreate/test_dlghotspotcreate.pro \
#src/backend/kylinipv4arping/kylinipv4arping-test.pro \
#src/backend/dbus/dbus-test.pro \
#src/backend/dbus_interface/dbus_interface-test.pro \
src/backend/dbus-interface/kylinconnectitem/kylinconnectitem-test.pro \
src/backend/dbus-interface/kylinactiveconnectresource/kylinactiveconnectresource-test.pro \
src/backend/dbus-interface/kyenterpricesettinginfo/kyenterpricesettinginfo-test.pro \
#src/backend/dbus-interface/kylinagent/kylinagent-test.pro \
src/backend/dbus-interface/kylinnetworkresourcemanager/kylinnetworkresourcemanager-test.pro \
#src/backend/dbus-interface/kylinvpnrequest/kylinvpnrequest-test.pro \
src/backend/dbus-interface/kylinvpnconnectitem/kylinvpnconnectitem-test.pro \
src/backend/dbus-interface/kylinutil/kylinutil-test.pro \
src/backend/dbus-interface/kylinconnectoperation/kylinconnectoperation-test.pro \
#src/backend/dbus-interface/kylinconnectresource/kylinconnectresource-test.pro \
#src/backend/dbus-interface/kywirelessnetitem/kywirelessnetitem-test.pro \
#src/backend/dbus-interface/kylinnetworkdeviceresource/kylinnetworkdeviceresource-test.pro \
src/backend/dbus-interface/kylinbluetoothconnectitem/kylinbluetoothconnectitem-test.pro \
src/backend/dbus-interface/kylinapconnectitem/kylinapconnectitem-test.pro \
#src/backend/dbus-interface/kylinsecretagent/kylinsecretagent-test.pro \
src/backend/dbus-interface/kylinconnectsetting/kylinconnectsetting-test.pro \
#src/backend/dbus-interface/kyvpnconnectoperation/kyvpnconnectoperation-test.pro \
src/backend/dbus-interface/kywirelessconnectoperation/kywirelessconnectoperation-test.pro \
#src/backend/dbus-interface/kylinwiredconnectoperation/kylinwiredconnectoperation-test.pro \
src/backend/sysdbusregister/sysdbusregister-test.pro \
#src/backend/wifi-auth-thread/wifi-auth-thread-test.pro \
src/backend/proxyservicemanager/proxyservicemanager-test.pro \
#src/backend/vpndbusadaptor/vpndbusadaptor-test.pro \
#src/backend/kylinipv6arping/kylinipv6arping-test.pro \
#src/backend/utils/utils-test.pro \
#src/main/test_main.pro \
src/frontend/customstyle/customstyle-test.pro \
src/frontend/netdetails/multiplednswidget/multiplednswidget-test.pro \
src/frontend/netdetails/creatnetpage/creatnetpage-test.pro \
src/frontend/netdetails/ipv4page/ipv4page-test.pro \
#src/frontend/netdetails/netdetail/netdetail-test.pro \
src/frontend/netdetails/ipv6page/ipv6page-test.pro \
src/frontend/netdetails/dnssettingwidget/dnssettingwidget-test.pro \
src/frontend/netdetails/joinhiddenwifipage/joinhiddenwifipage-test.pro \
src/frontend/netdetails/securitypage/securitypage-test.pro \
src/frontend/netdetails/customtabstyle/customtabstyle-test.pro \
src/frontend/netdetails/detailpage/detailpage-test.pro \
#src/frontend/connectivity/connectivitypage/connectivitypage-test.pro \
#src/frontend/tools/divider/divider-test.pro \
#src/frontend/tools/loadingdiv/loadingdiv-test.pro \
src/frontend/tools/listitemedit/listitemedit-test.pro \
#src/frontend/tools/kylable/kylable-test.pro \
#src/frontend/tools/radioitembutton/radioitembutton-test.pro \
#src/frontend/tools/infobutton/infobutton-test.pro \
#src/frontend/wificonfigdialog/wificonfigdialog-test.pro \
#src/frontend/mainwindow/mainwindow-test.pro \
#src/frontend/xatom/xatom-helper-test.pro \
#src/frontend/list-items/wlanlistitem/wlanlistitem-test.pro \
#src/frontend/list-items/wlanmoreitem/test_wlanmoreitem.pro \
#src/frontend/list-items/listitem/listitem-test.pro \
#src/frontend/list-items/lanlistitem/test_lanlistitem.pro \
#src/frontend/enterprise-wlan/enterprisewlandialog-test.pro \
#src/frontend/tab-pages/tabpage/tabpage-test.pro \
#src/frontend/tab-pages/wlanpage/wlanpage-test.pro \
#src/frontend/tab-pages/lanpage/lanpage-test.pro \
#src/frontend/networkmode/networkmodeconfig/networkmodeconfig-test.pro \
#src/frontend/networkmode/firewalldialog/firewalldialog-test.pro \
#src/singleapplication/qt-single-application-test.pro \
#src/singleapplication/test_qt-locked-file-unix/test_qt-locked-file-unix.pro \
#src/singleapplication/qt-local-peer/qt-local-peer-test.pro \
#src/singleapplication/qt-locked-file/qt-locked-file-test.pro \
pub/uisecurityconfig/uisecurityconfig-test.pro \
pub/appsettings/appsettings-test.pro \
kylin-network-manager-enhance-daemon/kylin-network-manager-enhance-daemon-test.pro \
