/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.kylin.weather.xml -a dbusadaptor -c DbusAdaptor -l MainWindow
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSADAPTOR_H
#define DBUSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include <QtDBus/QDBusMetaType>

#include "tabpage.h"
#include "../dbus-interface/kylinnetworkdeviceresource.h"
QT_BEGIN_NAMESPACE
class QByteArray;
//template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
template<class T> class QVector;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.kylin.weather
 */

#include "new-mainwindow.h"

class WiredInfo
{
    QString connName;
    QString uuid;

    friend QDBusArgument&operator <<(QDBusArgument&argument, const WiredInfo&arg)
    {
        argument.beginStructure();
        argument << arg.connName;
        argument << arg.uuid;
        argument.endStructure();
        return argument;
    }
    friend const QDBusArgument &operator >>(const QDBusArgument &argument, WiredInfo &arg)
    {
        argument.beginStructure();
        argument >> arg.connName;
        argument >> arg.uuid;
        argument.endStructure();
        return argument;
    }
};
Q_DECLARE_METATYPE(WiredInfo)

class WirelessInfo
{
    QString ssid;
    uint    signalStrength;
    bool    bSecu;

    friend QDBusArgument&operator <<(QDBusArgument&argument, const WirelessInfo&arg)
    {
        argument.beginStructure();
        argument << arg.ssid;
        argument << arg.signalStrength;
        argument << arg.bSecu;
        argument.endStructure();
        return argument;
    }
    friend const QDBusArgument &operator >>(const QDBusArgument&argument, WirelessInfo&arg)
    {
        argument.beginStructure();
        argument >> arg.ssid;
        argument >> arg.signalStrength;
        argument >> arg.bSecu;
        argument.endStructure();
        return argument;
    }
};
Q_DECLARE_METATYPE(WirelessInfo)

class DbusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.kylin.network")
public:
    DbusAdaptor(MainWindow *parent);
    virtual ~DbusAdaptor();

    inline MainWindow *parent() const
    { return static_cast<MainWindow *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    //无线列表
    QList<WirelessInfo> getWirelessList(QString devName);
    //有线列表
    QList<WiredInfo>  getWiredList(QString devName);
    //有线开关
    Q_NOREPLY void setWiredSwitchEnable(bool enable);
    //无线开关
    Q_NOREPLY void setWirelessSwitchEnable(bool enable);
    //启用/禁用网卡
    Q_NOREPLY void setDeviceEnable(QString devName, bool enable);
    //设置默认网卡
    Q_NOREPLY void setDefaultWiredDevice(QString deviceName);
    QString getDefaultWiredDevice();
    Q_NOREPLY void setDefaultWirelessDevice(QString deviceName);
    QString  getDefaultWirelessDevice();
    //连接 根据网卡类型 参数2 为ssid/uuid
    Q_NOREPLY void activateConnect(QString devName, QString ssid);
    //断开连接 根据网卡类型 参数2 为ssid/uuid
    Q_NOREPLY void deActivateConnect(QString devName, QString ssid);
    //获取设备列表和启用/禁用状态
    QMap<QString, bool> getDeviceListAndEnabled();
    //唤起属性页 根据网卡类型 参数2 为ssid/uuid
    Q_NOREPLY void showPropertyWidget(QString devName, QString ssid);
    //唤起新建有线连接界面
    Q_NOREPLY void showCreateWiredConnectWidget(QString devName, QString connectionName);
Q_SIGNALS: // SIGNALS
    void listUpdate(QString devName);
    void deviceUpdate();
    //仅失败，若成功直接发listUpdate
    void activateFinish(QString devName, QString ssid);
    //设备插拔
    void deviceStatusChanged();
    void deviceNameUpdate(QString oldName, QString newName);
};

#endif
