/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.kylin.weather.xml -a dbusadaptor -c DbusAdaptor -l MainWindow
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

const QByteArray GSETTINGS_SCHEMA_KYLIN_NM = "org.ukui.kylin-nm.switch";
const QString    KEY_WIRELESS_SWITCH          = "wirelessswitch";
const QString    KEY_WIRED_SWITCH             = "wiredswitch";

void saveDeviceEnableState(QString deviceName, bool enable)
{
    QSettings * m_settings = new QSettings(CONFIG_FILE_PATH, QSettings::IniFormat);
    m_settings->beginGroup("CARDEABLE");
    m_settings->setValue(deviceName, enable);
    m_settings->endGroup();
    m_settings->sync();
    delete m_settings;
    m_settings = nullptr;
    return;
}

bool getDeviceEnableState(QMap<QString, bool> &map)
{
    if (!QFile::exists(CONFIG_FILE_PATH)) {
        return false;
    }
    map.clear();

    KyNetworkDeviceResourse * kdr = new KyNetworkDeviceResourse();
    QStringList wiredDevList,wirelessDevList;
    wiredDevList.clear();
    wirelessDevList.clear();

    QSettings * m_settings = new QSettings(CONFIG_FILE_PATH, QSettings::IniFormat);
    m_settings->beginGroup("CARDEABLE");

    kdr->getNetworkDeviceList(NetworkManager::Device::Type::Ethernet, wiredDevList);
    if (!wiredDevList.isEmpty()) {
        for (int i = 0; i < wiredDevList.size(); ++i) {
            bool enable = m_settings->value(wiredDevList.at(i), true).toBool();
            map.insert(wiredDevList.at(i), enable);
        }
    }

    kdr->getNetworkDeviceList(NetworkManager::Device::Type::Wifi, wirelessDevList);
    if (!wirelessDevList.isEmpty()) {
        for (int i = 0; i < wirelessDevList.size(); ++i) {
            bool enable = m_settings->value(wirelessDevList.at(i), true).toBool();
            map.insert(wirelessDevList.at(i), enable);
        }
    }

    m_settings->endGroup();
    delete m_settings;
    m_settings = nullptr;
    delete kdr;
    kdr = nullptr;
    return true;
}

//设置默认网卡
void setDefaultDevice(KyDeviceType deviceType, QString deviceName)
{
    QString key;
    switch (deviceType) {
    case WIRED:
        key = "wired";
        break;
    case WIRELESS:
        key = "wireless";
        break;
    default:
        return;
        break;
    }
    QSettings * m_settings = new QSettings(CONFIG_FILE_PATH, QSettings::IniFormat);
    m_settings->beginGroup("DEFAULTCARD");
    m_settings->setValue(key, deviceName);
    m_settings->endGroup();
    m_settings->sync();
    delete m_settings;
    m_settings = nullptr;
    return;
}

bool checkDeviceExist(KyDeviceType deviceType, QString deviceName)
{
    NetworkManager::Device::Type type;
    switch (deviceType) {
    case WIRED:
        type = NetworkManager::Device::Type::Ethernet;
        break;
    case WIRELESS:
        type = NetworkManager::Device::Type::Wifi;
        break;
    default:
        return false;
        break;
    }

    KyNetworkDeviceResourse * kdr = new KyNetworkDeviceResourse();
    QStringList devList;
    devList.clear();

    kdr->getNetworkDeviceList(type, devList);
    return devList.contains(deviceName);
}

/*
 * Implementation of adaptor class DbusAdaptor
 */

DbusAdaptor::DbusAdaptor(MainWindow *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    qDBusRegisterMetaType<QMap<QString, bool> >();
    qDBusRegisterMetaType<QVector<QStringList> >();
    qDBusRegisterMetaType<QMap<QString, QVector<QStringList> >>();
    //setAutoRelaySignals(true)后会自动转发mainwindow发出的同名信号，因此不必再额外写一个转发
    setAutoRelaySignals(true);
}

DbusAdaptor::~DbusAdaptor()
{
    // destructor
}

//无线列表
QMap<QString, QVector<QStringList> > DbusAdaptor::getWirelessList()
{
    QMap<QString, QVector<QStringList> > map;
    parent()->getWirelessList(map);
    return map;
}

//有线列表
QMap<QString, QVector<QStringList>> DbusAdaptor::getWiredList()
{
    QMap<QString, QVector<QStringList>> map;
    parent()->getWiredList(map);
    return map;
}

//有线开关
void DbusAdaptor::setWiredSwitchEnable(bool enable)
{
    //todo mainwindow调用backend 对开关 打开/关闭
    if (QGSettings::isSchemaInstalled(GSETTINGS_SCHEMA_KYLIN_NM)) {
        QGSettings *gsetting = new QGSettings(GSETTINGS_SCHEMA_KYLIN_NM);
        gsetting->set(KEY_WIRED_SWITCH, enable);
    } else {
        qDebug()<<"isSchemaInstalled false";
    }
}

//无线开关
void DbusAdaptor::setWirelessSwitchEnable(bool enable)
{
    //todo mainwindow调用backend 对开关 打开/关闭
    if (QGSettings::isSchemaInstalled(GSETTINGS_SCHEMA_KYLIN_NM)) {
        QGSettings *gsetting = new QGSettings(GSETTINGS_SCHEMA_KYLIN_NM);
        gsetting->set(KEY_WIRELESS_SWITCH, enable);
        delete gsetting;
        gsetting = nullptr;
    } else {
        qDebug()<<"isSchemaInstalled false";
    }
}

//启用/禁用网卡
void DbusAdaptor::setDeviceEnable(QString devName, bool enable)
{
    saveDeviceEnableState(devName, enable);
}

//设置默认网卡
void DbusAdaptor::setDefaultWiredDevice(QString deviceName)
{
    if (!checkDeviceExist(WIRED, deviceName)) {
        return;
    }
    setDefaultDevice(WIRED, deviceName);
    parent()->setWiredDefaultDevice(deviceName);
    return;
}

QString DbusAdaptor::getDefaultWiredDevice()
{
    QSettings * m_settings = new QSettings(CONFIG_FILE_PATH, QSettings::IniFormat);
    m_settings->beginGroup("DEFAULTCARD");
    QString key("wired");
    QString deviceName = m_settings->value(key, "").toString();
    m_settings->endGroup();
    delete m_settings;
    m_settings = nullptr;
    return deviceName;
}

void DbusAdaptor::setDefaultWirelessDevice(QString deviceName)
{
    if (!checkDeviceExist(WIRED, deviceName)) {
        return;
    }
    setDefaultDevice(WIRELESS, deviceName);
    parent()->setWirelessDefaultDevice(deviceName);
    return;
}

QString  DbusAdaptor::getDefaultWirelessDevice()
{
    QSettings * m_settings = new QSettings(CONFIG_FILE_PATH, QSettings::IniFormat);
    m_settings->beginGroup("DEFAULTCARD");
    QString key("wireless");
    QString deviceName = m_settings->value(key, "").toString();
    m_settings->endGroup();
    delete m_settings;
    m_settings = nullptr;
    return deviceName;
}

//连接 根据网卡类型 参数1 0:lan 1:wlan 参数3 为ssid/uuid
void DbusAdaptor::activateConnect(int type, QString devName, QString ssid)
{
    if (type == 0) {
        parent()->activateWired(devName,ssid);
    } else if (type == 1) {
        parent()->activateWireless(devName,ssid);
    } else {
        qDebug() << "[DbusAdaptor] activateConnect type is invalid";
    }
}

//断开连接 根据网卡类型 参数1 0:lan 1:wlan 参数3 为ssid/uuid
void DbusAdaptor::deActivateConnect(int type, QString devName, QString ssid)
{
    if (type == 0) {
        parent()->deactivateWired(devName,ssid);
    } else if (type == 1) {
        parent()->deactivateWireless(devName,ssid);
    } else {
        qDebug() << "[DbusAdaptor] deactivateConnect type is invalid";
    }
}

//获取设备列表和启用/禁用状态
QMap<QString, bool> DbusAdaptor::getDeviceListAndEnabled()
{
    QMap<QString, bool> map;
    map.clear();
    getDeviceEnableState(map);
    return map;
}

//唤起属性页 根据网卡类型 参数2 为ssid/uuid
void DbusAdaptor::showPropertyWidget(QString devName, QString ssid)
{
    //todo
    //parent()->showPropertyWidget(devName,ssid);
}

//唤起新建有线连接界面
void DbusAdaptor::showCreateWiredConnectWidget(QString devName, QString connectionName)
{
    //todo
    //parent()->showCreateWiredConnectWidget(devName,connectionName);
}

//开启热点
void DbusAdaptor::activeWirelessAp(const QString apName, const QString apPassword, const QString apDevice)
{
    parent()->activeWirelessAp(apName, apPassword, apDevice);
}

//断开热点
void DbusAdaptor::deactiveWirelessAp(const QString apName, const QString apPassword, const QString apDevice)
{
    parent()->deactiveWirelessAp(apName, apPassword, apDevice);
}
