/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.kylin.weather.xml -a dbusadaptor -c DbusAdaptor -l MainWindow
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef VPNDBUSADAPTOR_H
#define VPNDBUSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include <QtDBus/QDBusMetaType>
#include <QStringList>
#include <QVector>
#include "singlepage.h"
#include "kylinnetworkdeviceresource.h"
#include "kyvpnconnectoperation.h"

QT_BEGIN_NAMESPACE
class QByteArray;
template<class Key, class Value> class QMap;
class QString;
class QVariant;
QT_END_NAMESPACE

#include "vpnobject.h"

class VpnDbusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.kylin.kylinvpn")
public:
    VpnDbusAdaptor(vpnObject *parent);

    inline vpnObject *parent() const
    { return static_cast<vpnObject *>(QObject::parent()); }

public Q_SLOTS:
    QVector<QStringList> getVirtualList();
    Q_NOREPLY void deleteVpn(QString uuid);
    Q_NOREPLY void activateVpn(const QString& connUuid);
    Q_NOREPLY void deactivateVpn(const QString& connUuid);
    Q_NOREPLY void showVpnAddWidget();
    Q_NOREPLY void showDetailPage(const QString& connUuid);

    void showKylinVpn();

Q_SIGNALS:
    void vpnAdd(QStringList info);
    void vpnRemove(QString dbusPath);
    void vpnUpdate(QStringList info);
    void vpnActiveConnectionStateChanged(QString uuid, int status);

    void activateFailed(QString errorMessage);
    void deactivateFailed(QString errorMessage);
};

#endif
