debian/kylin-nm.json /etc/ukui/ukui-notification/default-app/
debian/nm_enhance_dns.conf /etc/nm_enhance/
sys-dbus-register/conf/kylin-nm-sysdbus.service /lib/systemd/system/

# 将DBus安全策略配置文件安装到临时目录，在kylin-nm.postinst脚本中再将其移动到正确位置，以解决安装时该配置文件未替换的问题
sys-dbus-netctrl/conf/com.kylin.networkCtrol.yaml /usr/share/dbus-1/conf/.kylin-nm-yaml/
sys-dbus-register/conf/com.kylin.network.qt.systemdbus.yaml /usr/share/dbus-1/conf/.kylin-nm-yaml/
