/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.kylin.weather.xml -a dbusadaptor -c DbusAdaptor -l MainWindow
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "kylindbusadapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

const QByteArray GSETTINGS_SCHEMA_KYLIN_NM    = "org.ukui.kylin-nm.switch";
const QString    KEY_WIRELESS_SWITCH          = "wirelessswitch";
const QString    KEY_WIRED_SWITCH             = "wiredswitch";

/*
 * Implementation of adaptor class DbusAdaptor
 */

KylinDbusAdaptor::KylinDbusAdaptor(KylinDbusInterface *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    qDBusRegisterMetaType<QMap<QString, bool> >();
    qDBusRegisterMetaType<QMap<QString, int> >();
    qDBusRegisterMetaType<QVector<QStringList> >();
    qDBusRegisterMetaType<QMap<QString, QVector<QStringList> >>();
    //setAutoRelaySignals(true)后会自动转发kylindbusinterface发出的同名信号，因此不必再额外写一个转发
    setAutoRelaySignals(true);
}

KylinDbusAdaptor::~KylinDbusAdaptor()
{
    // destructor
}

//无线列表
QMap<QString, QVector<QStringList> > KylinDbusAdaptor::getWirelessList()
{
    QMap<QString, QVector<QStringList> > map;
    parent()->getWirelessList(map);
    return map;
}

//有线列表
QMap<QString, QVector<QStringList>> KylinDbusAdaptor::getWiredList()
{
    QMap<QString, QVector<QStringList>> map;
    parent()->getWiredList(map);
    return map;
}

//有线开关
void KylinDbusAdaptor::setWiredSwitchEnable(bool enable)
{

}

//无线开关
void KylinDbusAdaptor::setWirelessSwitchEnable(bool enable)
{
    parent()->setWirelessSwitchEnable(enable);
}

//启用/禁用网卡
void KylinDbusAdaptor::setDeviceEnable(QString devName, bool enable)
{
    parent()->setWiredDeviceEnable(devName, enable);
//    saveDeviceEnableState(devName, enable);
}

//连接 根据网卡类型 参数1 0:lan 1:wlan 参数3 为ssid/uuid
void KylinDbusAdaptor::activateConnect(int type, QString devName, QString ssid)
{
//    if (type == WIRED) {
//        parent()->activateWired(devName,ssid);
//    } else if (type == WIRELESS) {
//        parent()->activateWireless(devName,ssid);
//    } else {
//        qDebug() << "[DbusAdaptor] activateConnect type is invalid";
//    }
}

//断开连接 根据网卡类型 参数1 0:lan 1:wlan 参数3 为ssid/uuid
void KylinDbusAdaptor::deActivateConnect(int type, QString devName, QString ssid)
{
//    if (type == WIRED) {
//        qDebug()  << "deactivateWired";
//        parent()->deactivateWired(devName,ssid);
//    } else if (type == WIRELESS) {
//        parent()->deactivateWireless(devName,ssid);
//    } else {
//        qDebug() << "[DbusAdaptor] deactivateConnect type is invalid";
//    }
}

//获取设备列表和启用/禁用状态
/*
* 由于要读取配置文件的信息，配置文件的位置，可能在登录界面无法获取配置文件的内容
*/
QMap<QString, bool> KylinDbusAdaptor::getDeviceListAndEnabled(int devType)
{
    QMap<QString, bool> map;
    map.clear();
//    getDeviceEnableState(devType, map);
    return map;
}

//获取无线设备能力
QMap<QString, int> KylinDbusAdaptor::getWirelessDeviceCap()
{
    QMap<QString, int> map;
    parent()->getWirelessDeviceCapability(map);
    return map;
}

////唤起属性页 根据网卡类型 参数2 为ssid/uuid
//void KylinDbusAdaptor::showPropertyWidget(QString devName, QString ssid)
//{
//    qDebug() << "showPropertyWidget";
//    parent()->showPropertyWidget(devName,ssid);
//}

////唤起新建有线连接界面
//void KylinDbusAdaptor::showCreateWiredConnectWidget(QString devName)
//{
//    qDebug() << "showCreateWiredConnectWidget";
//    parent()->showCreateWiredConnectWidget(devName);
//}

//开启热点
void KylinDbusAdaptor::activeWirelessAp(const QString apName, const QString apPassword, const QString band, const QString apDevice)
{
    parent()->activeWirelessAp(apName, apPassword, band, apDevice);
}

//断开热点
void KylinDbusAdaptor::deactiveWirelessAp(const QString apName, const QString uuid)
{
    parent()->deactiveWirelessAp(apName, uuid);
}

//获取热点
QStringList KylinDbusAdaptor::getStoredApInfo()
{
    QStringList list;
    list.clear();
    parent()->getStoredApInfo(list);
    return list;
}

QStringList KylinDbusAdaptor::getApInfoBySsid(QString devName, QString ssid)
{
    QStringList list;
    list.clear();
    parent()->getApInfoBySsid(devName, ssid, list);
    return list;
}


//扫描
void KylinDbusAdaptor::reScan()
{
   parent()->rescanWireless();
}

void KylinDbusAdaptor::startAgent()
{
   parent()->startAgent();
}

void KylinDbusAdaptor::stopAgent()
{
   parent()->stopAgent();
}
