#ifndef LIBNMBASEKYLIN_GLOBAL_H
#define LIBNMBASEKYLIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBNMBASEKYLIN_LIBRARY)
#  define LIBNMBASEKYLIN_EXPORT Q_DECL_EXPORT
#else
#  define LIBNMBASEKYLIN_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBNMBASEKYLIN_GLOBAL_H
